airbnb:
  outputs:
    dev:
      type: snowflake
      account: kwirnxf-cu19045
      user: dbt

      role: TRANSFORM
      private_key: "-=\n-----END ENCRYPTED PRIVATE KEY-----\n"
      private_key_passphrase: q

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
